---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  # required here to acces cluster resoruces
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: foo-trig
      bindings:
        - name: pipeline-binding
        - name: message-binding
      template:
        name: pipeline-template
