---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: say-hello
spec:
  inputs:
    params:
      - name: contenttype
        description: The Content-Type of the event
        type: string
    resources:
      - name: git-source
        type: git
  steps:
    - name: say-hi
      image: bash
      command: ["bash", "-c"]
      args:
        - echo -e 'Hello Triggers!\nContent-Type is $(params.contenttype)'
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: say-message
spec:
  inputs:
    params:
      - name: message
        description: The message to print
        default: This is the default message
        type: string
    resources:
      - name: git-source
        type: git
  steps:
  - name: say-message
    image: bash
    command: ["bash", "-c"]
    args:
      - echo '$(params.message)'
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: say-bye
spec:
  inputs:
    resources:
      - name: git-source
        type: git
  steps:
  - name: say-bye
    image: bash
    command: ["bash", "-c"]
    args:
    - echo 'Goodbye Triggers!'

