apiVersion: v1
kind: Secret
metadata:
  name: github-ibm
  annotations:
    tekton.dev/git-0: github.com 
    tekton.dev/git-1: github.ibm.com 
type: kubernetes.io/ssh-auth
data:
  # cat ~/.ssh/id_rsa | base64 -w 0
  ssh-privatekey: 
  # This is non-standard, but its use is encouraged to make this more secure.
  # ssh-keyscan github.com | base64 -w 0
  # or
  # cat ~/.ssh/known_hosts | base64 -w 0
  known_hosts: 




