apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
  - name: gitrevision
    #value: $(body.head_commit.id)
    value: $(body.repository.master_branch)
  - name: gitrepositoryurl
    value: $(body.repository.ssh_url)
  - name: contenttype
    value: $(header.Content-Type)
